apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pyecho_service_name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.app_name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app_port }}
      protocol: TCP
      name: http
